### ISSUE TITLE
CrashLoopBackOff on Calico and Canal

### ISSUE THREAD

**Issue by sauber** [rancher/klipper-lb#6]
When using Calico og Canal as the cluster network driver, klipper-lb fails to start up pods for LoadBalancer services.

From a default k3s installation on ubuntu 20.04 with only Flannel disabled, and either Calico or Canal added:

```
:~$ kubectl -n kube-system get ds/svclb-traefik
NAME            DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
svclb-traefik   1         1         0       1            0           <none>          13m
:~$ kubectl -n kube-system get pod -l app=svclb-traefik
NAME                  READY   STATUS             RESTARTS   AGE
svclb-traefik-85mxm   0/2     CrashLoopBackOff   14         13m
:~$ kubectl -n kube-system logs ds/svclb-traefik lb-port-80
+ trap exit TERM INT
/usr/bin/entry: line 6: can't create /proc/sys/net/ipv4/ip_forward: Read-only file system
+ echo 1
+ true
+ cat /proc/sys/net/ipv4/ip_forward
+ '[' 0 '!=' 1 ]
+ exit 1
:~$
```

**Comment by BlankZhu** [comment]
> When using Calico og Canal as the cluster network driver, klipper-lb fails to start up pods for LoadBalancer services.
>
> From a default k3s installation on ubuntu 20.04 with only Flannel disabled, and either Calico or Canal added:
>
> ```
> :~$ kubectl -n kube-system get ds/svclb-traefik
> NAME            DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
> svclb-traefik   1         1         0       1            0           <none>          13m
> :~$ kubectl -n kube-system get pod -l app=svclb-traefik
> NAME                  READY   STATUS             RESTARTS   AGE
> svclb-traefik-85mxm   0/2     CrashLoopBackOff   14         13m
> :~$ kubectl -n kube-system logs ds/svclb-traefik lb-port-80
> + trap exit TERM INT
> /usr/bin/entry: line 6: can't create /proc/sys/net/ipv4/ip_forward: Read-only file system
> + echo 1
> + true
> + cat /proc/sys/net/ipv4/ip_forward
> + '[' 0 '!=' 1 ]
> + exit 1
> :~$
> ```

Calico uses `"allow_ip_forwarding": false` as default.
Try adding  `"allow_ip_forwarding": true` to calico's cni_network_config like below:

```yaml
{
  "name": "k8s-pod-network",
  "cniVersion": "0.3.1",
  "plugins":
    [
      {
        "type": "calico",
        "log_level": "info",
        "datastore_type": "kubernetes",
        "nodename": "__KUBERNETES_NODE_NAME__",
        "mtu": __CNI_MTU__,
        "ipam": { "type": "calico-ipam" },
        "policy": { "type": "k8s" },
        "kubernetes": { "kubeconfig": "__KUBECONFIG_FILEPATH__" },
        "container_settings": { "allow_ip_forwarding": true },  # ADD THIS
      },
      {
        "type": "portmap",
        "snat": true,
        "capabilities": { "portMappings": true },
      },
      { "type": "bandwidth", "capabilities": { "bandwidth": true } },
    ],
}
```

The container should run normally.

It works for me, and, I'm getting some logs from lb-port-80/lb-port-443 like below:

```shell
+ trap exit TERM INT
/usr/bin/entry: line 6: can't create /proc/sys/net/ipv4/ip_forward: Read-only file system
+ echo 1
+ true
+ cat /proc/sys/net/ipv4/ip_forward
+ '[' 1 '!=' 1 ]
+ iptables -t nat -I PREROUTING '!' -s 10.43.199.158/32 -p TCP --dport 80 -j DNAT --to 10.43.199.158:80
+ iptables -t nat -I POSTROUTING -d 10.43.199.158/32 -p TCP -j MASQUERADE
+ '[' '!' -e /pause ]
+ mkfifo /pause
```

Anyway, my Ingress works normally and the status of lb-port-80/lb-port-443 is `Running`. Hope this helps.
